spring.application.name=ConnectO
server.port=8080
jwt.secret = iqurhnwiujhfw8cjuiofkjchr33298375298hwnifufcwhejf98472
zego.appId = 159164384
zego.serverSecret = 14b5a9278d3c26dba6a6cc6976eb891e
spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/static/