spring.application.name=Chat-App
server.port=5000
jwt.secret = iqurhnwiujhfw8cjuiofkjchr33298375298hwnifufcwhejf98472
logging.level.root=ERROR
zego.appId = 159164384
zego.serverSecret = 14b5a9278d3c26dba6a6cc6976eb891e